-- File analyses table
CREATE TABLE file_analyses (
  id BIGSERIAL PRIMARY KEY,
  analysis_id TEXT UNIQUE NOT NULL,
  file_name TEXT NOT NULL,
  file_format TEXT NOT NULL,
  file_type TEXT NOT NULL,
  analysis_results JSONB NOT NULL,
  extracted_data JSONB NOT NULL,
  insights JSONB NOT NULL,
  visualizations JSONB NOT NULL,
  citations JSONB NOT NULL,
  uploaded_at TIMESTAMP DEFAULT NOW(),
  processed_at TIMESTAMP DEFAULT NOW()
);

-- Sample sequences table for proteins and RNA
CREATE TABLE sample_sequences (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  sequence_type TEXT NOT NULL, -- 'protein' or 'rna'
  sequence TEXT NOT NULL,
  header TEXT,
  description TEXT,
  organism TEXT,
  gene_name TEXT,
  function_description TEXT,
  length INTEGER,
  gc_content DOUBLE PRECISION,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX idx_file_analyses_analysis_id ON file_analyses(analysis_id);
CREATE INDEX idx_file_analyses_uploaded_at ON file_analyses(uploaded_at);
CREATE INDEX idx_file_analyses_file_format ON file_analyses(file_format);
CREATE INDEX idx_sample_sequences_type ON sample_sequences(sequence_type);
CREATE INDEX idx_sample_sequences_name ON sample_sequences(name);

-- Insert sample protein sequences
INSERT INTO sample_sequences (name, sequence_type, sequence, header, description, organism, gene_name, function_description, length, gc_content) VALUES
(
  'Human Insulin',
  'protein',
  'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN',
  '>sp|P01308|INS_HUMAN Insulin OS=Homo sapiens OX=9606 GN=INS PE=1 SV=1',
  'Insulin hormone precursor protein from human pancreatic beta cells',
  'Homo sapiens',
  'INS',
  'Hormone that regulates blood glucose levels by facilitating cellular glucose uptake',
  110,
  NULL
),
(
  'E. coli Beta-Lactamase',
  'protein', 
  'MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRIDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPVAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW',
  '>sp|P62593|BLAT_ECOLI Beta-lactamase TEM-1 OS=Escherichia coli OX=562 GN=bla PE=1 SV=1',
  'TEM-1 beta-lactamase enzyme conferring antibiotic resistance',
  'Escherichia coli',
  'bla',
  'Hydrolyzes beta-lactam antibiotics including penicillins and some cephalosporins',
  286,
  NULL
),
(
  'Green Fluorescent Protein',
  'protein',
  'MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITLGMDELYK',
  '>sp|P42212|GFP_AEQVI Green fluorescent protein OS=Aequorea victoria OX=6100 GN=GFP PE=1 SV=1',
  'Wild-type green fluorescent protein from jellyfish',
  'Aequorea victoria',
  'GFP',
  'Fluorescent protein that emits green light when excited by blue light',
  238,
  NULL
),
(
  'SARS-CoV-2 Spike Protein RBD',
  'protein',
  'RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQDVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEHVNNSYECDIPIGAGICASYQTQTNSPRRARSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKDFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALNTLVKQLSSNFGAISSVLNDILSRLDKVEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQYIKWPWYIWLGFIAGLIAIVMVTIMLCCMTSCCSCLKGCCSCGSCCKFDEDDSEPVLKGVKLHYT',
  '>sp|P0DTC2|SPIKE_SARS2 Spike glycoprotein OS=Severe acute respiratory syndrome coronavirus 2 OX=2697049 GN=S PE=1 SV=1',
  'Receptor-binding domain of SARS-CoV-2 spike protein',
  'SARS-CoV-2',
  'S',
  'Viral spike protein that binds to human ACE2 receptor for cell entry',
  685,
  NULL
),
(
  'Cas9 Nuclease',
  'protein',
  'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGETAEATRLKRTARRRYTRRKNRICYLQEIFSNEMAKVDDSFFHRLEESFLVEEDKKHERHPIFGNIVDEVAYHEKYPTIYHLRKKLVDSTDKADLRLIYLALAHMIKFRGHFLIEGDLNPDNSDVDKLFIQLVQTYNQLFEENPINASGVDAKAILSARLSKSRRLENLIAQLPGEKKNGLFGNLIALSLGLTPNFKSNFDLAEDAKLQLSKDTYDDDLDNLLAQIGDQYADLFLAAKNLSDAILLSDILRVNTEITKAPLSASMIKRYDEHHQDLTLLKALVRQQLPEKYKEIFFDQSKNGYAGYIDGGASQEEFYKFIKPILEKMDGTEELLVKLNREDLLRKQRTFDNGSIPHQIHLGELHAILRRQEDFYPFLKDNREKIEKILTFRIPYYVGPLARGNSRFAWMTRKSEETITPWNFEEVVDKGASAQSFIERMTNFDKNLPNEKVLPKHSLLYEYFTVYNELTKVKYVTEGMRKPAFLSGEQKKAIVDLLFKTNRKVTVKQLKEDYFKKIECFDSVEISGVEDRFNASLGTYHDLLKIIKDKDFLDNEENEDILEDIVLTLTLFEDREMIIEERLKTYAHLFDDKVMKQLKRRRYTGWGRLSRKLINGIRDKQSGKTILDFLKSDGFANRNFMQLIHDDSLTFKEDIQKAQVSGQGDSLHEHIANLAGSPAIKKGILQTVKVVDELVKVMGRHKPENIVIEMARENQTTQKGQKNSRERMKRIEEGIKELGSQILKEHPVENTQLQNEKLYLYYLQNGRDMYVDQELDINRLSDYDVDHIVPQSFLKDDSIDNKVLTRSDKNRGKSDNVPSEEVVKKMKNYWRQLLNAKLITQRKFDNLTKAERGGLSELDKAGFIKRQLVETRQITKHVAQILDSRMNTKYDENDKLIREVKVITLKSKLVSDFRKDFQFYKVREINNYHHAHDAYLNAVVGTALIKKYPKLESEFVYGDYKVYDVRKMIAKSEQEIGKATAKYFFYSNIMNFFKTEITLANGEIRKRPLIETNGETGEIVWDKGRDFATVRKVLSMPQVNIVKKTEVQTGGFSKESILPKRNSDKLIARKKDWDPKKYGGFDSPTVAYSVLVVAKVEKGKSKKLKSVKELLGITIMERSSFEKNPIDFLEAKGYKEVKKDLIIKLPKYSLFELENGRKRMLASAGELQKGNELALPSKYVNFLYLASHYEKLKGSPEDNEQKQLFVEQHKHYLDEIIEQISEFSKRVILADANLDKVLSAYNKHRDKPIREQAENIIHLFTLTNLGAPAAFKYFDTTIDRKRYTSTKEVLDATLIHQSITGLYETRIDLSQLGGD',
  '>sp|Q99ZW2|CAS9_STRP1 CRISPR-associated endonuclease Cas9 OS=Streptococcus pyogenes serotype M1 OX=301447 GN=cas9 PE=1 SV=1',
  'CRISPR-associated protein 9 nuclease from Streptococcus pyogenes',
  'Streptococcus pyogenes',
  'cas9',
  'RNA-guided DNA endonuclease for genome editing applications',
  1368,
  NULL
);

-- Insert sample RNA sequences
INSERT INTO sample_sequences (name, sequence_type, sequence, header, description, organism, gene_name, function_description, length, gc_content) VALUES
(
  'Human tRNA-Phe',
  'rna',
  'GCGGAUUUAGCUCAGUUGGGAGAGCGCCAGACUGAAGAUCUGGAGGUCCUGUGUUCGAUCCACAGAAUUCGCA',
  '>Human tRNA-Phe (UUC/F) mitochondrial',
  'Human mitochondrial phenylalanine transfer RNA',
  'Homo sapiens',
  'TRNF',
  'Transfer RNA that delivers phenylalanine to the ribosome during protein synthesis',
  71,
  0.5915
),
(
  'E. coli 16S rRNA Fragment',
  'rna',
  'UAAGGAGGUGGCAAGCGUUAUCCGGAAUUAUUGGGCGUAAAGCGCACGCAGGCGGUUUGAUAAGUCCGAUGUCUAAAGCCCCGGCUCAACCGGGGAGGUGCAUCCGAUACUGGCAAGCUUGAGUUCUCGUAGAGGGGGGAGAAUCUCAAGUUCGAAGUCCCGGCUCCACAACGUGCUUACUGCUUGCCUUCGGUAAUGGCUGAGAAUGUGAAGACCUGCCUGACUUUCUGGGAAAUAGUGUGACGGUACCGCAGAAUAAGCACCGGCUAACUCCGUGCCAGCAGCCGCGGUAAUACGGAGGGUGCAAGCGUUAAUCGGAAUUACUGGGCGUAAAGCGCACGCAGGCGGUUUGAUAAGGCCGAUGUGUCUAGAGCCCCGGCUCAACCGGGGAGGUGCAUCUCGAUACUGGCAAGCUUGAGUUCUCGUAGAGGGGGGAGAAUCUCAAGUUCGAAGUCCUGGCUCCACAACGUGCCUACUGCUUGCCUUCGGUAAUGGCUGAGAAUGUGAAGACCUGCCUGACUUUCUGGGAAAUAGUGUGACGGUACCGCAGAAUAAGCACCGGCUAACUCCGUGCCAGCAGCCGCGGUAAUACGGAGGGUGCAAGCGUUAAUCGGAAUUACUGGGCGUAAAGCGCACGCAGGCGGUUUGAUAAGGCCGAUGUGUCU',
  '>E. coli 16S ribosomal RNA partial sequence',
  'Partial sequence of Escherichia coli 16S ribosomal RNA',
  'Escherichia coli',
  '16S rRNA',
  'Component of 30S ribosomal subunit involved in protein synthesis and phylogenetic classification',
  507,
  0.5187
),
(
  'SARS-CoV-2 5'' UTR',
  'rna',
  'AUUAAAGGUU UAUACCUUCC CAGGUAACAA ACCAACCAAC UUUCGAUCUC UUGCCGAAUC CCUAAUAUGU AAUUGUUGGG UUUCAAAGCA AAUGCUGAUC CUCAAGCAAA AGGUAUUUAC CCACUAAAUC CAUCCCUCAA GACUACAUUU UUGAAAGAUG AAGGAUUCAC UGCAAAUUGA UAAUUUGGUU CAAUAAUACA AACAUUAAUU UUCUGAUGAA AGAAAUAGCA AACAUUUUGU AAUUGAAAUG AAAGAGUAAU GUUAUUUCAG AACACUAAAA UGGUGAAGAU GCACAUGUAA CCACAUUCCG CUGAAAUUGU AAUUGGCUGU AUUGCUUUGG GUUUUGCCAU UUUGAAAGCA AUCCCCUGAA AUAAUUAAUU CAAUAAAUCA ACAAAAAAGC UUAAAACUAC ACAAAAACAC AAUUCAAUGU GGUGGUAGUU GGCAUUCUAG CUGCUAAAUU GGCAAGUAAU AAAUGUGCUG UAAAGACUAA AUCUUAUAUU UAACUUUGGG UAAUGGUAUU UUGGUAACCA AAGGUGGUUC CGGUACUUAC CAGAAACAAA UUUAUUGAAA ACUUGAGAGG UACAAGGCGA AAAAGAAACG CGUACGUGGU GCUUCUUUAA GUAGUGGGAA ACCUGAAGAA AUGAGAACAG UGAAGAUAUU',
  '>SARS-CoV-2 5'' untranslated region',
  '5'' untranslated region of SARS-CoV-2 genome containing regulatory elements',
  'SARS-CoV-2',
  '5'' UTR',
  'Regulatory region controlling viral RNA translation and replication',
  265,
  0.3849
),
(
  'Human microRNA let-7a',
  'rna',
  'UGAGGUAGUAGGUUGUAUAGUU',
  '>hsa-let-7a-5p mature microRNA',
  'Human let-7a mature microRNA sequence',
  'Homo sapiens',
  'let-7a',
  'MicroRNA involved in regulation of cell proliferation and differentiation',
  22,
  0.4091
),
(
  'Ribozyme Hammerhead',
  'rna',
  'CUGAGGAGGCCGAAGGACGAAACGGUGAAGAUUGUAGAAGCCGUCGAAGGAGUCGGGACUCUGCCGGGUACCGCAGGGUUAAGGAGGAACUGAAAGAAGGUCGUAACAAGGCUGCAGGAGUCAAGACGGUGACUUGGGCAUUUCUUCAACC',
  '>Hammerhead ribozyme sequence',
  'Catalytic RNA molecule with self-cleaving activity',
  'Synthetic',
  'hammerhead ribozyme',
  'Self-cleaving catalytic RNA used in gene regulation and therapeutic applications',
  134,
  0.5299
),
(
  'Bacterial RNase P RNA',
  'rna',
  'GGGCGCGUAGGCGCCAAGUGGGUCCCGGUUCGAUUCCGGGCGCGUCCCGUACUGCGGACGUUCGAUCCGUGCGAGUAGGCGCAAUGUGGGGUUCGAAUCUCCCGUUCGCGCCCAGGAGUCACGCCGGCGGGGUUCGAAUCUCCCGUUCGCGCCCACCGCGCUGAUUUCUCAGUGGCGCGCCGUCAGUCGAAUUGGGACGGGUUGCAAGCCGGGGUGAGGAAGUCGAAUUGGGACGGGUUGCAAGCCGGGGUGAGGAAGUCUUCUCAG',
  '>Bacterial RNase P RNA catalytic subunit',
  'Catalytic RNA component of bacterial RNase P ribonucleoprotein',
  'Escherichia coli',
  'rnpB',
  'Catalytic RNA that processes precursor tRNAs by cleaving 5'' leader sequences',
  243,
  0.5556
);
